* configure: Regen. 	* configure.in: Check for broken Cygwin grep 	and generate an error if found. 	* config/acinclude.m4 (CYG_AC_PATH_TCLH, 	CYG_AC_PATH_TKH): Rework tests so they depend 	on $host instead of a hard coded check to 	see if CC is set to "cl".

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -631,6 +631,20 @@ test "$host_alias" != "$target_alias" &&
   program_prefix=${target_alias}-
 
 
+# When compiling with VC++ under Cygwin, we need to
+# check for a grep executable that does not treat
+# CRLF the same as LF. This problem causes a number
+# of really mysterious configure problems.
+
+case "${host}" in
+*windows32*)
+        result=`echo file.cA | tr A '\r' | grep -v '^file.c$'`
+        if test "$result" = "file.c" ; then
+            { echo "configure: error: Can't build with Cygwin grep, see INSTALL.TXT" 1>&2; exit 1; }
+        fi
+        ;;
+esac
+
 TOP_SUBDIRS="tcl tk itcl tix libgui db snavigator"
 
 subdirs="$TOP_SUBDIRS"
